### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by guy-withThe-hat** [HumabHatterZed/WhistleWindInscryptionMods#28]
[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayAbilityIcons (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayInfo (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardRenderCamera+<UpdateTextureWhenReady>d__18.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
DiskCardGame.CardRenderCamera:QueueStatsLayerForRender(CardRenderInfo, RenderStatsLayer, PlayableCard, Boolean, Boolean)
DiskCardGame.RenderStatsLayer:RenderCard(CardRenderInfo)
DiskCardGame.Card:RenderCard()
DiskCardGame.Card:SetInfo(CardInfo)
DiskCardGame.SelectableCard:Initialize(CardInfo, Action`1, Action`1, Boolean, Action`1)
DiskCardGame.<CardSelectionSequence>d__13:MoveNext()
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
DiskCardGame.SpecialNodeHandler:StartSpecialNodeSequence(SpecialNodeData)
DiskCardGame.<TransitionTo>d__34:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.UpdateInteractableIcons () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.SetInfo (DiskCardGame.CardInfo info) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.SelectableCard.Initialize (DiskCardGame.CardInfo info, System.Action`1[T] cardSelected, System.Action`1[T] cardFlipped, System.Boolean startFlipped, System.Action`1[T] cardInspected) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardSingleChoicesSequencer+<CardSelectionSequence>d__13.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
DiskCardGame.SpecialNodeHandler:StartSpecialNodeSequence(SpecialNodeData)
DiskCardGame.<TransitionTo>d__34:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by HumabHatterZed** [comment]
What part of the game did you experience the error?

**Comment by guy-withThe-hat** [comment]
During the node where you select 3 cards, when the card with particles is placed no more cards are placed down and I can't do anything. The game stops working, but the ~ and the esc key still work.

![error](https://github.com/HumabHatterZed/WhistleWindInscryptionMods/assets/43190491/cbc57cbe-4810-4918-b7a4-cf3503eb766b)

Here's the error in the console again:

[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayAbilityIcons (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayInfo (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardRenderCamera+<UpdateTextureWhenReady>d__18.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
DiskCardGame.CardRenderCamera:QueueStatsLayerForRender(CardRenderInfo, RenderStatsLayer, PlayableCard, Boolean, Boolean)
DiskCardGame.RenderStatsLayer:RenderCard(CardRenderInfo)
DiskCardGame.Card:RenderCard()
DiskCardGame.Card:SetInfo(CardInfo)
DiskCardGame.SelectableCard:Initialize(CardInfo, Action`1, Action`1, Boolean, Action`1)
DiskCardGame.<CardSelectionSequence>d__13:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.UpdateInteractableIcons () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.SetInfo (DiskCardGame.CardInfo info) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.SelectableCard.Initialize (DiskCardGame.CardInfo info, System.Action`1[T] cardSelected, System.Action`1[T] cardFlipped, System.Boolean startFlipped, System.Action`1[T] cardInspected) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardSingleChoicesSequencer+<CardSelectionSequence>d__13.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)

**Comment by guy-withThe-hat** [comment]
Another error during the trader:

![error2](https://github.com/HumabHatterZed/WhistleWindInscryptionMods/assets/43190491/12ad7c41-402c-4bcf-bd8c-56274df6609a)

Console Error:

[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayAbilityIcons (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardDisplayer3D.DisplayInfo (DiskCardGame.CardRenderInfo renderInfo, DiskCardGame.PlayableCard playableCard) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardRenderCamera+<UpdateTextureWhenReady>d__18.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
DiskCardGame.CardRenderCamera:QueueStatsLayerForRender(CardRenderInfo, RenderStatsLayer, PlayableCard, Boolean, Boolean)
DiskCardGame.RenderStatsLayer:RenderCard(CardRenderInfo)
DiskCardGame.Card:RenderCard()
DiskCardGame.Card:SetInfo(CardInfo)
DiskCardGame.<CreateTradeCards>d__20:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: key
Parameter name: Null key
Stack trace:
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetValue (TKey key, System.Runtime.CompilerServices.ConditionalWeakTable`2+CreateValueCallback[TKey,TValue] createValueCallback) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
System.Runtime.CompilerServices.ConditionalWeakTable`2[TKey,TValue].GetOrCreateValue (TKey key) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
InscryptionAPI.Card.AbilityManager.GetAbilityExtensionTable (DiskCardGame.AbilityInfo info) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.AbilityInfo info, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
InscryptionAPI.Card.AbilityExtensions.GetExtendedProperty (DiskCardGame.Ability ability, System.String propertyName) (at <f974655283b54d49aa3bf95b5211a619>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)
System.Collections.Generic.List`1[T].RemoveAll (System.Predicate`1[T] match) (at <44afb4564e9347cf99a1865351ea8f4a>:0)
WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)
DiskCardGame.CardAbilityIcons.GetDistinctShownAbilities (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.CardAbilityIcons.UpdateAbilityIcons (DiskCardGame.CardInfo info, System.Collections.Generic.List`1[T] mods, DiskCardGame.PlayableCard playableCard, System.Collections.Generic.List`1[T] hiddenAbilities) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.UpdateInteractableIcons () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.RenderCard () (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.Card.SetInfo (DiskCardGame.CardInfo info) (at <4bde92741da1454db82522c215e393a6>:0)
DiskCardGame.TradePeltsSequencer+<CreateTradeCards>d__20.MoveNext () (at <4bde92741da1454db82522c215e393a6>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <3f8c35799b544274b189c23afcaaf82e>:0)



The lines that involve Abnormal Sigils:

`WhistleWind.AbnormalSigils.Core.StatusEffectPatches+<>c.<DontRenderStatusEffectsNormally>b__0_0 (DiskCardGame.Ability x) (at <7a97906b335a4719a92dffc8fc689b15>:0)`

`WhistleWind.AbnormalSigils.Core.StatusEffectPatches.DontRenderStatusEffectsNormally (System.Collections.Generic.List`1[DiskCardGame.Ability]& __result) (at <7a97906b335a4719a92dffc8fc689b15>:0)`
